import {Box, Stack, Typography} from "@mui/material";
import React from "react";
import StartRoundedIcon from "@mui/icons-material/StartRounded";
import OutlinedFlagIcon from "@mui/icons-material/OutlinedFlag";
import SubtitlesOutlinedIcon from "@mui/icons-material/SubtitlesOutlined";
import MultipleStopRoundedIcon from "@mui/icons-material/MultipleStopRounded";
import UpdateRoundedIcon from "@mui/icons-material/UpdateRounded";
import QuestionMarkOutlined from "@mui/icons-material/QuestionMarkOutlined";
import {useTheme} from "@mui/material";
import TooltipTypography from "./TooltipTypography";
import {CheckCircleOutlined, StopCircleOutlined} from "@mui/icons-material";

export enum TransactionTypeName {
  BlockMetadata = "block_metadata_transaction",
  Genesis = "genesis_transaction",
  User = "user_transaction",
  Pending = "pending_transaction",
  StateCheckpoint = "state_checkpoint_transaction",
  Validator = "validator_transaction",
  BlockEpilogue = "block_epilogue_transaction",
  Unknown = "unknown",
}

type Color = "inherit" | "primary" | undefined;

function getTypeLabel(type: string): string {
  switch (type) {
    case TransactionTypeName.BlockMetadata:
      return "Block Metadata";
    case TransactionTypeName.Genesis:
      return "Genesis Transaction";
    case TransactionTypeName.User:
      return "User Transaction";
    case TransactionTypeName.Pending:
      return "Pending Transaction";
    case TransactionTypeName.StateCheckpoint:
      return "State Checkpoint";
    case TransactionTypeName.Validator:
      return "Validator Transaction";
    case TransactionTypeName.BlockEpilogue:
      return "Block Epilogue Transaction";
    default:
      return `Unknown type: ${type}`;
  }
}

function getTypeIcon(type: string, color?: Color) {
  switch (type) {
    case TransactionTypeName.BlockMetadata:
      return <SubtitlesOutlinedIcon fontSize="small" color={color} />;
    case TransactionTypeName.Genesis:
      return <StartRoundedIcon fontSize="small" color={color} />;
    case TransactionTypeName.User:
      return <MultipleStopRoundedIcon fontSize="small" color={color} />;
    case TransactionTypeName.Pending:
      return <UpdateRoundedIcon fontSize="small" color={color} />;
    case TransactionTypeName.StateCheckpoint:
      return <OutlinedFlagIcon fontSize="small" color={color} />;
    case TransactionTypeName.Validator:
      return <CheckCircleOutlined fontSize="small" color={color} />;
    case TransactionTypeName.BlockEpilogue:
      return <StopCircleOutlined fontSize="small" color={color} />;
    default:
      return <QuestionMarkOutlined fontSize="small" color={color} />;
  }
}

function getTypeTooltip(type: string): string {
  switch (type) {
    case TransactionTypeName.BlockMetadata:
      return "System-generated transactions that provide additional data for each confirmed block.";
    case TransactionTypeName.Genesis:
      return "The first transaction in the Aptos blockchain.";
    case TransactionTypeName.User:
      return "A transaction generated by users of the Aptos blockchain.";
    case TransactionTypeName.Pending:
      return "A transaction currently in the mempool waiting to be committed.";
    case TransactionTypeName.StateCheckpoint:
      return "System-generated transactions that save the latest state of the Aptos blockchain.";
    case TransactionTypeName.Validator:
      return "Validator metadata transactions.";
    case TransactionTypeName.BlockEpilogue:
      return "Block epilogue transactions describing end state of a block.";
    default:
      return `Unknown transaction type ${type}.`;
  }
}

type TransactionTypeProps = {
  type: string;
};

export function TransactionType({type}: TransactionTypeProps) {
  const theme = useTheme();
  return (
    <Box
      sx={{
        display: "flex",
        alignItems: "center",
        gap: 1,
        color: theme.palette.text.secondary,
      }}
    >
      {getTypeIcon(type, "inherit")}
      <Typography variant="body2">{getTypeLabel(type)}</Typography>
    </Box>
  );
}

export function TableTransactionType({type}: TransactionTypeProps) {
  return (
    <Box sx={{display: "flex", alignItems: "center"}}>
      {getTypeIcon(type, "inherit")}
    </Box>
  );
}

export function TooltipTransactionType({type}: TransactionTypeProps) {
  return (
    <Box sx={{display: "flex", alignItems: "flex-start", gap: 2}}>
      {getTypeIcon(type, "inherit")}
      <Stack spacing={0.5}>
        <TooltipTypography variant="subtitle2" fontWeight={600}>
          {getTypeLabel(type)}
        </TooltipTypography>
        <TooltipTypography variant="body2">
          {getTypeTooltip(type)}
        </TooltipTypography>
      </Stack>
    </Box>
  );
}
