/* biome-ignore-all lint: generated by wasm-pack */
/* @ts-self-types="./move_compiler_wasm.d.ts" */

/**
 * Compilation result returned to JavaScript
 */
export class CompilationResult {
  static __wrap(ptr) {
    ptr = ptr >>> 0;
    const obj = Object.create(CompilationResult.prototype);
    obj.__wbg_ptr = ptr;
    CompilationResultFinalization.register(obj, obj.__wbg_ptr, obj);
    return obj;
  }
  __destroy_into_raw() {
    const ptr = this.__wbg_ptr;
    this.__wbg_ptr = 0;
    CompilationResultFinalization.unregister(this);
    return ptr;
  }
  free() {
    const ptr = this.__destroy_into_raw();
    wasm.__wbg_compilationresult_free(ptr, 0);
  }
  /**
   * Get compiled bytecode (only if successful)
   * @returns {Uint8Array}
   */
  get bytecode() {
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      wasm.compilationresult_bytecode(retptr, this.__wbg_ptr);
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      var v1 = getArrayU8FromWasm0(r0, r1).slice();
      wasm.__wbindgen_export(r0, r1 * 1, 1);
      return v1;
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
    }
  }
  /**
   * Get compilation errors as JSON array
   * @returns {string}
   */
  get errors() {
    let deferred1_0;
    let deferred1_1;
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      wasm.compilationresult_errors(retptr, this.__wbg_ptr);
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      deferred1_0 = r0;
      deferred1_1 = r1;
      return getStringFromWasm0(r0, r1);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
      wasm.__wbindgen_export(deferred1_0, deferred1_1, 1);
    }
  }
  /**
   * Check if compilation was successful
   * @returns {boolean}
   */
  get success() {
    const ret = wasm.compilationresult_success(this.__wbg_ptr);
    return ret !== 0;
  }
  /**
   * Get full result as JSON
   * @returns {string}
   */
  toJSON() {
    let deferred1_0;
    let deferred1_1;
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      wasm.compilationresult_toJSON(retptr, this.__wbg_ptr);
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      deferred1_0 = r0;
      deferred1_1 = r1;
      return getStringFromWasm0(r0, r1);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
      wasm.__wbindgen_export(deferred1_0, deferred1_1, 1);
    }
  }
  /**
   * Get compilation warnings as JSON array
   * @returns {string}
   */
  get warnings() {
    let deferred1_0;
    let deferred1_1;
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      wasm.compilationresult_warnings(retptr, this.__wbg_ptr);
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      deferred1_0 = r0;
      deferred1_1 = r1;
      return getStringFromWasm0(r0, r1);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
      wasm.__wbindgen_export(deferred1_0, deferred1_1, 1);
    }
  }
}
if (Symbol.dispose)
  CompilationResult.prototype[Symbol.dispose] =
    CompilationResult.prototype.free;

/**
 * In-memory Move package builder for WASM
 *
 * This allows building Move packages entirely in memory without filesystem access.
 * JavaScript provides all source files and dependencies.
 */
export class MovePackage {
  __destroy_into_raw() {
    const ptr = this.__wbg_ptr;
    this.__wbg_ptr = 0;
    MovePackageFinalization.unregister(this);
    return ptr;
  }
  free() {
    const ptr = this.__destroy_into_raw();
    wasm.__wbg_movepackage_free(ptr, 0);
  }
  /**
   * Add a named address mapping
   * @param {string} name
   * @param {string} address
   */
  add_address(name, address) {
    const ptr0 = passStringToWasm0(
      name,
      wasm.__wbindgen_export2,
      wasm.__wbindgen_export3,
    );
    const len0 = WASM_VECTOR_LEN;
    const ptr1 = passStringToWasm0(
      address,
      wasm.__wbindgen_export2,
      wasm.__wbindgen_export3,
    );
    const len1 = WASM_VECTOR_LEN;
    wasm.movepackage_add_address(this.__wbg_ptr, ptr0, len0, ptr1, len1);
  }
  /**
   * Add a dependency
   * @param {string} name
   * @param {string} path
   */
  add_dependency(name, path) {
    const ptr0 = passStringToWasm0(
      name,
      wasm.__wbindgen_export2,
      wasm.__wbindgen_export3,
    );
    const len0 = WASM_VECTOR_LEN;
    const ptr1 = passStringToWasm0(
      path,
      wasm.__wbindgen_export2,
      wasm.__wbindgen_export3,
    );
    const len1 = WASM_VECTOR_LEN;
    wasm.movepackage_add_dependency(this.__wbg_ptr, ptr0, len0, ptr1, len1);
  }
  /**
   * Add a source file to the package
   *
   * # Arguments
   * * `path` - Relative path like "sources/MyModule.move"
   * * `content` - Move source code
   * @param {string} path
   * @param {string} content
   */
  add_source(path, content) {
    const ptr0 = passStringToWasm0(
      path,
      wasm.__wbindgen_export2,
      wasm.__wbindgen_export3,
    );
    const len0 = WASM_VECTOR_LEN;
    const ptr1 = passStringToWasm0(
      content,
      wasm.__wbindgen_export2,
      wasm.__wbindgen_export3,
    );
    const len1 = WASM_VECTOR_LEN;
    wasm.movepackage_add_source(this.__wbg_ptr, ptr0, len0, ptr1, len1);
  }
  /**
   * Build the package and generate bytecode for all modules
   *
   * # Returns
   * CompilationResult with combined bytecode or errors
   * @returns {CompilationResult}
   */
  build() {
    const ret = wasm.movepackage_build(this.__wbg_ptr);
    return CompilationResult.__wrap(ret);
  }
  /**
   * Get package metadata as JSON
   * @returns {string}
   */
  get_metadata() {
    let deferred1_0;
    let deferred1_1;
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      wasm.movepackage_get_metadata(retptr, this.__wbg_ptr);
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      deferred1_0 = r0;
      deferred1_1 = r1;
      return getStringFromWasm0(r0, r1);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
      wasm.__wbindgen_export(deferred1_0, deferred1_1, 1);
    }
  }
  /**
   * Get list of source files
   * @returns {string[]}
   */
  get_sources() {
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      wasm.movepackage_get_sources(retptr, this.__wbg_ptr);
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      var v1 = getArrayJsValueFromWasm0(r0, r1).slice();
      wasm.__wbindgen_export(r0, r1 * 4, 4);
      return v1;
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
    }
  }
  /**
   * Create a new Move package
   * @param {string} name
   * @param {string} version
   */
  constructor(name, version) {
    const ptr0 = passStringToWasm0(
      name,
      wasm.__wbindgen_export2,
      wasm.__wbindgen_export3,
    );
    const len0 = WASM_VECTOR_LEN;
    const ptr1 = passStringToWasm0(
      version,
      wasm.__wbindgen_export2,
      wasm.__wbindgen_export3,
    );
    const len1 = WASM_VECTOR_LEN;
    const ret = wasm.movepackage_new(ptr0, len0, ptr1, len1);
    this.__wbg_ptr = ret >>> 0;
    MovePackageFinalization.register(this, this.__wbg_ptr, this);
    return this;
  }
}
if (Symbol.dispose)
  MovePackage.prototype[Symbol.dispose] = MovePackage.prototype.free;

/**
 * Package metadata for Move.toml
 */
export class PackageMetadata {
  __destroy_into_raw() {
    const ptr = this.__wbg_ptr;
    this.__wbg_ptr = 0;
    PackageMetadataFinalization.unregister(this);
    return ptr;
  }
  free() {
    const ptr = this.__destroy_into_raw();
    wasm.__wbg_packagemetadata_free(ptr, 0);
  }
  /**
   * Add an address mapping
   * @param {string} name
   * @param {string} address
   */
  add_address(name, address) {
    const ptr0 = passStringToWasm0(
      name,
      wasm.__wbindgen_export2,
      wasm.__wbindgen_export3,
    );
    const len0 = WASM_VECTOR_LEN;
    const ptr1 = passStringToWasm0(
      address,
      wasm.__wbindgen_export2,
      wasm.__wbindgen_export3,
    );
    const len1 = WASM_VECTOR_LEN;
    wasm.packagemetadata_add_address(this.__wbg_ptr, ptr0, len0, ptr1, len1);
  }
  /**
   * Add a dependency
   * @param {string} name
   * @param {string} path
   */
  add_dependency(name, path) {
    const ptr0 = passStringToWasm0(
      name,
      wasm.__wbindgen_export2,
      wasm.__wbindgen_export3,
    );
    const len0 = WASM_VECTOR_LEN;
    const ptr1 = passStringToWasm0(
      path,
      wasm.__wbindgen_export2,
      wasm.__wbindgen_export3,
    );
    const len1 = WASM_VECTOR_LEN;
    wasm.packagemetadata_add_dependency(this.__wbg_ptr, ptr0, len0, ptr1, len1);
  }
  /**
   * Create new package metadata
   * @param {string} name
   * @param {string} version
   */
  constructor(name, version) {
    const ptr0 = passStringToWasm0(
      name,
      wasm.__wbindgen_export2,
      wasm.__wbindgen_export3,
    );
    const len0 = WASM_VECTOR_LEN;
    const ptr1 = passStringToWasm0(
      version,
      wasm.__wbindgen_export2,
      wasm.__wbindgen_export3,
    );
    const len1 = WASM_VECTOR_LEN;
    const ret = wasm.packagemetadata_new(ptr0, len0, ptr1, len1);
    this.__wbg_ptr = ret >>> 0;
    PackageMetadataFinalization.register(this, this.__wbg_ptr, this);
    return this;
  }
  /**
   * Convert to JSON
   * @returns {string}
   */
  toJSON() {
    let deferred1_0;
    let deferred1_1;
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      wasm.packagemetadata_toJSON(retptr, this.__wbg_ptr);
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      deferred1_0 = r0;
      deferred1_1 = r1;
      return getStringFromWasm0(r0, r1);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
      wasm.__wbindgen_export(deferred1_0, deferred1_1, 1);
    }
  }
}
if (Symbol.dispose)
  PackageMetadata.prototype[Symbol.dispose] = PackageMetadata.prototype.free;

/**
 * Compile a single Move module from source code (filesystem-free!)
 *
 * # Arguments
 * * `source` - Move source code
 * * `address` - Named address for the module (e.g., "0x1")
 * * `module_name` - Name of the module
 *
 * # Returns
 * CompilationResult with bytecode or errors
 *
 * # Implementation
 * Uses the new `run_move_compiler_from_sources()` API - no temp files needed!
 * @param {string} source
 * @param {string} address
 * @param {string} module_name
 * @returns {CompilationResult}
 */
export function compile_module(source, address, module_name) {
  const ptr0 = passStringToWasm0(
    source,
    wasm.__wbindgen_export2,
    wasm.__wbindgen_export3,
  );
  const len0 = WASM_VECTOR_LEN;
  const ptr1 = passStringToWasm0(
    address,
    wasm.__wbindgen_export2,
    wasm.__wbindgen_export3,
  );
  const len1 = WASM_VECTOR_LEN;
  const ptr2 = passStringToWasm0(
    module_name,
    wasm.__wbindgen_export2,
    wasm.__wbindgen_export3,
  );
  const len2 = WASM_VECTOR_LEN;
  const ret = wasm.compile_module(ptr0, len0, ptr1, len1, ptr2, len2);
  return CompilationResult.__wrap(ret);
}

/**
 * Compile a single Move module with additional dependency sources.
 *
 * `deps_json` is a JSON array of `{"path":"...", "content":"..."}` objects.
 * These are treated as library sources (dependencies) so the compiler can
 * resolve `use` imports that are not part of the bundled move-stdlib.
 *
 * `extra_named_addresses_json` is a JSON object like `{"name":"0x1",...}`.
 * @param {string} source
 * @param {string} address
 * @param {string} module_name
 * @param {string} deps_json
 * @param {string} extra_named_addresses_json
 * @returns {CompilationResult}
 */
export function compile_module_with_deps(
  source,
  address,
  module_name,
  deps_json,
  extra_named_addresses_json,
) {
  const ptr0 = passStringToWasm0(
    source,
    wasm.__wbindgen_export2,
    wasm.__wbindgen_export3,
  );
  const len0 = WASM_VECTOR_LEN;
  const ptr1 = passStringToWasm0(
    address,
    wasm.__wbindgen_export2,
    wasm.__wbindgen_export3,
  );
  const len1 = WASM_VECTOR_LEN;
  const ptr2 = passStringToWasm0(
    module_name,
    wasm.__wbindgen_export2,
    wasm.__wbindgen_export3,
  );
  const len2 = WASM_VECTOR_LEN;
  const ptr3 = passStringToWasm0(
    deps_json,
    wasm.__wbindgen_export2,
    wasm.__wbindgen_export3,
  );
  const len3 = WASM_VECTOR_LEN;
  const ptr4 = passStringToWasm0(
    extra_named_addresses_json,
    wasm.__wbindgen_export2,
    wasm.__wbindgen_export3,
  );
  const len4 = WASM_VECTOR_LEN;
  const ret = wasm.compile_module_with_deps(
    ptr0,
    len0,
    ptr1,
    len1,
    ptr2,
    len2,
    ptr3,
    len3,
    ptr4,
    len4,
  );
  return CompilationResult.__wrap(ret);
}

/**
 * Compile a Move script from source code (filesystem-free!)
 * @param {string} source
 * @param {string} address
 * @returns {CompilationResult}
 */
export function compile_script(source, address) {
  const ptr0 = passStringToWasm0(
    source,
    wasm.__wbindgen_export2,
    wasm.__wbindgen_export3,
  );
  const len0 = WASM_VECTOR_LEN;
  const ptr1 = passStringToWasm0(
    address,
    wasm.__wbindgen_export2,
    wasm.__wbindgen_export3,
  );
  const len1 = WASM_VECTOR_LEN;
  const ret = wasm.compile_script(ptr0, len0, ptr1, len1);
  return CompilationResult.__wrap(ret);
}

/**
 * Get library version and build information
 * @returns {string}
 */
export function get_version_info() {
  let deferred1_0;
  let deferred1_1;
  try {
    const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
    wasm.get_version_info(retptr);
    var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
    var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
    deferred1_0 = r0;
    deferred1_1 = r1;
    return getStringFromWasm0(r0, r1);
  } finally {
    wasm.__wbindgen_add_to_stack_pointer(16);
    wasm.__wbindgen_export(deferred1_0, deferred1_1, 1);
  }
}

/**
 * Initialize panic hook for better error messages in browser console
 */
export function init_panic_hook() {
  wasm.init_panic_hook();
}

function __wbg_get_imports() {
  const import0 = {
    __proto__: null,
    __wbg___wbindgen_throw_6ddd609b62940d55: function (arg0, arg1) {
      throw new Error(getStringFromWasm0(arg0, arg1));
    },
    __wbindgen_cast_0000000000000001: function (arg0, arg1) {
      // Cast intrinsic for `Ref(String) -> Externref`.
      const ret = getStringFromWasm0(arg0, arg1);
      return addHeapObject(ret);
    },
  };
  return {
    __proto__: null,
    "./move_compiler_wasm_bg.js": import0,
  };
}

const CompilationResultFinalization =
  typeof FinalizationRegistry === "undefined"
    ? {register: () => {}, unregister: () => {}}
    : new FinalizationRegistry((ptr) =>
        wasm.__wbg_compilationresult_free(ptr >>> 0, 1),
      );
const MovePackageFinalization =
  typeof FinalizationRegistry === "undefined"
    ? {register: () => {}, unregister: () => {}}
    : new FinalizationRegistry((ptr) =>
        wasm.__wbg_movepackage_free(ptr >>> 0, 1),
      );
const PackageMetadataFinalization =
  typeof FinalizationRegistry === "undefined"
    ? {register: () => {}, unregister: () => {}}
    : new FinalizationRegistry((ptr) =>
        wasm.__wbg_packagemetadata_free(ptr >>> 0, 1),
      );

function addHeapObject(obj) {
  if (heap_next === heap.length) heap.push(heap.length + 1);
  const idx = heap_next;
  heap_next = heap[idx];

  heap[idx] = obj;
  return idx;
}

function dropObject(idx) {
  if (idx < 1028) return;
  heap[idx] = heap_next;
  heap_next = idx;
}

function getArrayJsValueFromWasm0(ptr, len) {
  ptr = ptr >>> 0;
  const mem = getDataViewMemory0();
  const result = [];
  for (let i = ptr; i < ptr + 4 * len; i += 4) {
    result.push(takeObject(mem.getUint32(i, true)));
  }
  return result;
}

function getArrayU8FromWasm0(ptr, len) {
  ptr = ptr >>> 0;
  return getUint8ArrayMemory0().subarray(ptr / 1, ptr / 1 + len);
}

let cachedDataViewMemory0 = null;
function getDataViewMemory0() {
  if (
    cachedDataViewMemory0 === null ||
    cachedDataViewMemory0.buffer.detached === true ||
    (cachedDataViewMemory0.buffer.detached === undefined &&
      cachedDataViewMemory0.buffer !== wasm.memory.buffer)
  ) {
    cachedDataViewMemory0 = new DataView(wasm.memory.buffer);
  }
  return cachedDataViewMemory0;
}

function getStringFromWasm0(ptr, len) {
  ptr = ptr >>> 0;
  return decodeText(ptr, len);
}

let cachedUint8ArrayMemory0 = null;
function getUint8ArrayMemory0() {
  if (
    cachedUint8ArrayMemory0 === null ||
    cachedUint8ArrayMemory0.byteLength === 0
  ) {
    cachedUint8ArrayMemory0 = new Uint8Array(wasm.memory.buffer);
  }
  return cachedUint8ArrayMemory0;
}

function getObject(idx) {
  return heap[idx];
}

let heap = new Array(1024).fill(undefined);
heap.push(undefined, null, true, false);

let heap_next = heap.length;

function passStringToWasm0(arg, malloc, realloc) {
  if (realloc === undefined) {
    const buf = cachedTextEncoder.encode(arg);
    const ptr = malloc(buf.length, 1) >>> 0;
    getUint8ArrayMemory0()
      .subarray(ptr, ptr + buf.length)
      .set(buf);
    WASM_VECTOR_LEN = buf.length;
    return ptr;
  }

  let len = arg.length;
  let ptr = malloc(len, 1) >>> 0;

  const mem = getUint8ArrayMemory0();

  let offset = 0;

  for (; offset < len; offset++) {
    const code = arg.charCodeAt(offset);
    if (code > 0x7f) break;
    mem[ptr + offset] = code;
  }
  if (offset !== len) {
    if (offset !== 0) {
      arg = arg.slice(offset);
    }
    ptr = realloc(ptr, len, (len = offset + arg.length * 3), 1) >>> 0;
    const view = getUint8ArrayMemory0().subarray(ptr + offset, ptr + len);
    const ret = cachedTextEncoder.encodeInto(arg, view);

    offset += ret.written;
    ptr = realloc(ptr, len, offset, 1) >>> 0;
  }

  WASM_VECTOR_LEN = offset;
  return ptr;
}

function takeObject(idx) {
  const ret = getObject(idx);
  dropObject(idx);
  return ret;
}

let cachedTextDecoder = new TextDecoder("utf-8", {
  ignoreBOM: true,
  fatal: true,
});
cachedTextDecoder.decode();
const MAX_SAFARI_DECODE_BYTES = 2146435072;
let numBytesDecoded = 0;
function decodeText(ptr, len) {
  numBytesDecoded += len;
  if (numBytesDecoded >= MAX_SAFARI_DECODE_BYTES) {
    cachedTextDecoder = new TextDecoder("utf-8", {
      ignoreBOM: true,
      fatal: true,
    });
    cachedTextDecoder.decode();
    numBytesDecoded = len;
  }
  return cachedTextDecoder.decode(
    getUint8ArrayMemory0().subarray(ptr, ptr + len),
  );
}

const cachedTextEncoder = new TextEncoder();

if (!("encodeInto" in cachedTextEncoder)) {
  cachedTextEncoder.encodeInto = function (arg, view) {
    const buf = cachedTextEncoder.encode(arg);
    view.set(buf);
    return {
      read: arg.length,
      written: buf.length,
    };
  };
}

let WASM_VECTOR_LEN = 0;

let wasmModule, wasm;
function __wbg_finalize_init(instance, module) {
  wasm = instance.exports;
  wasmModule = module;
  cachedDataViewMemory0 = null;
  cachedUint8ArrayMemory0 = null;
  return wasm;
}

async function __wbg_load(module, imports) {
  if (typeof Response === "function" && module instanceof Response) {
    if (typeof WebAssembly.instantiateStreaming === "function") {
      try {
        return await WebAssembly.instantiateStreaming(module, imports);
      } catch (e) {
        const validResponse = module.ok && expectedResponseType(module.type);

        if (
          validResponse &&
          module.headers.get("Content-Type") !== "application/wasm"
        ) {
          console.warn(
            "`WebAssembly.instantiateStreaming` failed because your server does not serve Wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:\n",
            e,
          );
        } else {
          throw e;
        }
      }
    }

    const bytes = await module.arrayBuffer();
    return await WebAssembly.instantiate(bytes, imports);
  } else {
    const instance = await WebAssembly.instantiate(module, imports);

    if (instance instanceof WebAssembly.Instance) {
      return {instance, module};
    } else {
      return instance;
    }
  }

  function expectedResponseType(type) {
    switch (type) {
      case "basic":
      case "cors":
      case "default":
        return true;
    }
    return false;
  }
}

function initSync(module) {
  if (wasm !== undefined) return wasm;

  if (module !== undefined) {
    if (Object.getPrototypeOf(module) === Object.prototype) {
      ({module} = module);
    } else {
      console.warn(
        "using deprecated parameters for `initSync()`; pass a single object instead",
      );
    }
  }

  const imports = __wbg_get_imports();
  if (!(module instanceof WebAssembly.Module)) {
    module = new WebAssembly.Module(module);
  }
  const instance = new WebAssembly.Instance(module, imports);
  return __wbg_finalize_init(instance, module);
}

async function __wbg_init(module_or_path) {
  if (wasm !== undefined) return wasm;

  if (module_or_path !== undefined) {
    if (Object.getPrototypeOf(module_or_path) === Object.prototype) {
      ({module_or_path} = module_or_path);
    } else {
      console.warn(
        "using deprecated parameters for the initialization function; pass a single object instead",
      );
    }
  }

  if (module_or_path === undefined) {
    module_or_path = new URL("move_compiler_wasm_bg.wasm", import.meta.url);
  }
  const imports = __wbg_get_imports();

  if (
    typeof module_or_path === "string" ||
    (typeof Request === "function" && module_or_path instanceof Request) ||
    (typeof URL === "function" && module_or_path instanceof URL)
  ) {
    module_or_path = fetch(module_or_path);
  }

  const {instance, module} = await __wbg_load(await module_or_path, imports);

  return __wbg_finalize_init(instance, module);
}

export {__wbg_init as default, initSync};
