/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from "../runtime";
/**
 *
 * @export
 * @interface DeleteModule
 */
export interface DeleteModule {
  /**
   *
   * @type {string}
   * @memberof DeleteModule
   */
  type: string;
  /**
   * Hex-encoded 16 bytes Diem account address.
   *
   * Prefixed with `0x` and leading zeros are trimmed.
   *
   * See [doc](https://diem.github.io/move/address.html) for more details.
   * @type {string}
   * @memberof DeleteModule
   */
  address: string;
  /**
   * Move module id is a string representation of Move module.
   *
   * Format: "{address}::{module name}"
   *
   * `address` should be hex-encoded 16 bytes account address
   * that is prefixed with `0x` and leading zeros are trimmed.
   *
   * Module name is case sensitive.
   *
   * See [doc](https://diem.github.io/move/modules-and-scripts.html#modules) for more details.
   * @type {string}
   * @memberof DeleteModule
   */
  module: string;
}

export function DeleteModuleFromJSON(json: any): DeleteModule {
  return DeleteModuleFromJSONTyped(json, false);
}

export function DeleteModuleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeleteModule {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: json["type"],
    address: json["address"],
    module: json["module"],
  };
}

export function DeleteModuleToJSON(value?: DeleteModule | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: value.type,
    address: value.address,
    module: value.module,
  };
}
