/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Event,
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
} from './Event';
import {
    WriteSetChange,
    WriteSetChangeFromJSON,
    WriteSetChangeFromJSONTyped,
    WriteSetChangeToJSON,
} from './WriteSetChange';

/**
 * 
 * @export
 * @interface DirectWriteSet
 */
export interface DirectWriteSet {
    /**
     * 
     * @type {string}
     * @memberof DirectWriteSet
     */
    type: string;
    /**
     * 
     * @type {Array<WriteSetChange>}
     * @memberof DirectWriteSet
     */
    changes: Array<WriteSetChange>;
    /**
     * 
     * @type {Array<Event>}
     * @memberof DirectWriteSet
     */
    events: Array<Event>;
}

export function DirectWriteSetFromJSON(json: any): DirectWriteSet {
    return DirectWriteSetFromJSONTyped(json, false);
}

export function DirectWriteSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectWriteSet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'changes': ((json['changes'] as Array<any> || []).map(WriteSetChangeFromJSON)),
        'events': ((json['events'] as Array<any> || []).map(EventFromJSON)),
    };
}

export function DirectWriteSetToJSON(value?: DirectWriteSet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'changes': ((value.changes as Array<any> || []).map(WriteSetChangeToJSON)),
        'events': ((value.events as Array<any> || []).map(EventToJSON)),
    };
}

