/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Please refer to https://github.com/diem/diem/tree/main/specifications/crypto#signature-and-verification for
 * more details.
 * @export
 * @interface Ed25519Signature
 */
export interface Ed25519Signature {
    /**
     * 
     * @type {string}
     * @memberof Ed25519Signature
     */
    type: string;
    /**
     * All bytes data are represented as hex-encoded string prefixed with `0x` and fulfilled with
     * two hex digits per byte.
     * 
     * Different with `Address` type, hex-encoded bytes should not trim any zeros.
     * @type {string}
     * @memberof Ed25519Signature
     */
    publicKey: string;
    /**
     * All bytes data are represented as hex-encoded string prefixed with `0x` and fulfilled with
     * two hex digits per byte.
     * 
     * Different with `Address` type, hex-encoded bytes should not trim any zeros.
     * @type {string}
     * @memberof Ed25519Signature
     */
    signature: string;
}

export function Ed25519SignatureFromJSON(json: any): Ed25519Signature {
    return Ed25519SignatureFromJSONTyped(json, false);
}

export function Ed25519SignatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ed25519Signature {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'publicKey': json['public_key'],
        'signature': json['signature'],
    };
}

export function Ed25519SignatureToJSON(value?: Ed25519Signature | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'public_key': value.publicKey,
        'signature': value.signature,
    };
}

