/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LedgerInfo
 */
export interface LedgerInfo {
    /**
     * The blockchain chain id.
     * @type {number}
     * @memberof LedgerInfo
     */
    chainId: number;
    /**
     * The version of the latest transaction in the ledger.
     * @type {string}
     * @memberof LedgerInfo
     */
    ledgerVersion: string;
    /**
     * Timestamp in microseconds, e.g. ledger / block creation timestamp.
     * @type {string}
     * @memberof LedgerInfo
     */
    ledgerTimestamp: string;
}

export function LedgerInfoFromJSON(json: any): LedgerInfo {
    return LedgerInfoFromJSONTyped(json, false);
}

export function LedgerInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LedgerInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chainId': json['chain_id'],
        'ledgerVersion': json['ledger_version'],
        'ledgerTimestamp': json['ledger_timestamp'],
    };
}

export function LedgerInfoToJSON(value?: LedgerInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chain_id': value.chainId,
        'ledger_version': value.ledgerVersion,
        'ledger_timestamp': value.ledgerTimestamp,
    };
}

