/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MoveModule,
    MoveModuleFromJSON,
    MoveModuleFromJSONTyped,
    MoveModuleToJSON,
} from './MoveModule';

/**
 * 
 * @export
 * @interface ModuleBundlePayload
 */
export interface ModuleBundlePayload {
    /**
     * 
     * @type {string}
     * @memberof ModuleBundlePayload
     */
    type: string;
    /**
     * 
     * @type {Array<MoveModule>}
     * @memberof ModuleBundlePayload
     */
    modules: Array<MoveModule>;
}

export function ModuleBundlePayloadFromJSON(json: any): ModuleBundlePayload {
    return ModuleBundlePayloadFromJSONTyped(json, false);
}

export function ModuleBundlePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModuleBundlePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'modules': ((json['modules'] as Array<any> || []).map(MoveModuleFromJSON)),
    };
}

export function ModuleBundlePayloadToJSON(value?: ModuleBundlePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'modules': ((value.modules as Array<any> || []).map(MoveModuleToJSON)),
    };
}

