/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from "../runtime";
/**
 *
 * @export
 * @interface MoveStructField
 */
export interface MoveStructField {
  /**
   *
   * @type {string}
   * @memberof MoveStructField
   */
  name: string;
  /**
   * String representation of an on-chain Move type identifier defined by the Move language.
   *
   * Values:
   *   - bool
   *   - u8
   *   - u64
   *   - u128
   *   - address
   *   - signer
   *   - vector: `vector<{non-reference MoveTypeId}>`
   *   - struct: `{address}::{module_name}::{struct_name}::<{generic types}>`
   *   - reference: immutable `&` and mutable `&mut` references.
   *   - generic_type_parameter: it is always start with `T` and following an index number,
   *     which is the position of the generic type parameter in the `struct` or
   *     `function` generic type parameters definition.
   *
   * Vector type value examples:
   *   * `vector<u8>`
   *   * `vector<vector<u64>>`
   *   * `vector<0x1::DiemAccount::Balance<0x1::XDX::XDX>>`
   *
   * Struct type value examples:
   *   * `0x1::Diem::Diem<0x1::XDX::XDX>`
   *   * `0x1::Abc::Abc<vector<u8>, vector<u64>>`
   *   * `0x1::DiemAccount::AccountOperationsCapability`
   *
   * Reference type value examples:
   *   * `&signer`
   *   * `&mut address`
   *   * `&mut vector<u8>`
   *
   * Generic type parameter value example, the following is `0x1::TransactionFee::TransactionFee` JSON representation:
   *
   *     {
   *         "name": "TransactionFee",
   *         "is_native": false,
   *         "abilities": ["key"],
   *         "generic_type_params": [
   *             {"constraints": [], "is_phantom": true}
   *         ],
   *         "fields": [
   *             { "name": "balance", "type": "0x1::Diem::Diem<T0>" },
   *             { "name": "preburn", "type": "0x1::Diem::Preburn<T0>" }
   *         ]
   *     }
   *
   * It's Move source code:
   *
   *     module DiemFramework::TransactionFee {
   *         struct TransactionFee<phantom CoinType> has key {
   *             balance: Diem<CoinType>,
   *             preburn: Preburn<CoinType>,
   *         }
   *     }
   *
   * The `T0` in the above JSON representation is the generic type place holder for
   * the `CoinType` in the Move source code.
   *
   * Note:
   *   1. Empty chars should be ignored when comparing 2 struct tag ids.
   *   2. When used in an URL path, should be encoded by url-encoding (AKA percent-encoding).
   * @type {string}
   * @memberof MoveStructField
   */
  type: string;
}

export function MoveStructFieldFromJSON(json: any): MoveStructField {
  return MoveStructFieldFromJSONTyped(json, false);
}

export function MoveStructFieldFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MoveStructField {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"],
    type: json["type"],
  };
}

export function MoveStructFieldToJSON(value?: MoveStructField | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    type: value.type,
  };
}
