/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from "../runtime";
import {
  MoveFunction,
  MoveFunctionFromJSON,
  MoveFunctionFromJSONTyped,
  MoveFunctionToJSON,
} from "./MoveFunction";

/**
 *
 * @export
 * @interface MoveScript
 */
export interface MoveScript {
  /**
   * All bytes data are represented as hex-encoded string prefixed with `0x` and fulfilled with
   * two hex digits per byte.
   *
   * Different with `Address` type, hex-encoded bytes should not trim any zeros.
   * @type {string}
   * @memberof MoveScript
   */
  bytecode: string;
  /**
   *
   * @type {MoveFunction}
   * @memberof MoveScript
   */
  abi?: MoveFunction;
}

export function MoveScriptFromJSON(json: any): MoveScript {
  return MoveScriptFromJSONTyped(json, false);
}

export function MoveScriptFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MoveScript {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    bytecode: json["bytecode"],
    abi: !exists(json, "abi") ? undefined : MoveFunctionFromJSON(json["abi"]),
  };
}

export function MoveScriptToJSON(value?: MoveScript | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    bytecode: value.bytecode,
    abi: MoveFunctionToJSON(value.abi),
  };
}
