/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MoveAbility,
    MoveAbilityFromJSON,
    MoveAbilityFromJSONTyped,
    MoveAbilityToJSON,
} from './MoveAbility';

/**
 * 
 * @export
 * @interface MoveFunctionGenericTypeParams
 */
export interface MoveFunctionGenericTypeParams {
    /**
     * 
     * @type {Array<MoveAbility>}
     * @memberof MoveFunctionGenericTypeParams
     */
    constraints: Array<MoveAbility>;
}

export function MoveFunctionGenericTypeParamsFromJSON(json: any): MoveFunctionGenericTypeParams {
    return MoveFunctionGenericTypeParamsFromJSONTyped(json, false);
}

export function MoveFunctionGenericTypeParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoveFunctionGenericTypeParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'constraints': ((json['constraints'] as Array<any> || []).map(MoveAbilityFromJSON)),
    };
}

export function MoveFunctionGenericTypeParamsToJSON(value?: MoveFunctionGenericTypeParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'constraints': ((value.constraints as Array<any> || []).map(MoveAbilityToJSON)),
    };
}

