/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OnChainTransactionInfo
 */
export interface OnChainTransactionInfo {
    /**
     * Unsiged int64 type value
     * @type {string}
     * @memberof OnChainTransactionInfo
     */
    version: string;
    /**
     * All bytes data are represented as hex-encoded string prefixed with `0x` and fulfilled with
     * two hex digits per byte.
     * 
     * Different with `Address` type, hex-encoded bytes should not trim any zeros.
     * @type {string}
     * @memberof OnChainTransactionInfo
     */
    hash: string;
    /**
     * All bytes data are represented as hex-encoded string prefixed with `0x` and fulfilled with
     * two hex digits per byte.
     * 
     * Different with `Address` type, hex-encoded bytes should not trim any zeros.
     * @type {string}
     * @memberof OnChainTransactionInfo
     */
    stateRootHash: string;
    /**
     * All bytes data are represented as hex-encoded string prefixed with `0x` and fulfilled with
     * two hex digits per byte.
     * 
     * Different with `Address` type, hex-encoded bytes should not trim any zeros.
     * @type {string}
     * @memberof OnChainTransactionInfo
     */
    eventRootHash: string;
    /**
     * Unsiged int64 type value
     * @type {string}
     * @memberof OnChainTransactionInfo
     */
    gasUsed: string;
    /**
     * Transaction execution result (success: true, failure: false).
     * See `vm_status` for human readable error message from Diem VM.
     * @type {boolean}
     * @memberof OnChainTransactionInfo
     */
    success: boolean;
    /**
     * Human readable transaction execution result message from Diem VM.
     * @type {string}
     * @memberof OnChainTransactionInfo
     */
    vmStatus: string;
    /**
     * All bytes data are represented as hex-encoded string prefixed with `0x` and fulfilled with
     * two hex digits per byte.
     * 
     * Different with `Address` type, hex-encoded bytes should not trim any zeros.
     * @type {string}
     * @memberof OnChainTransactionInfo
     */
    accumulatorRootHash: string;
}

export function OnChainTransactionInfoFromJSON(json: any): OnChainTransactionInfo {
    return OnChainTransactionInfoFromJSONTyped(json, false);
}

export function OnChainTransactionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnChainTransactionInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': json['version'],
        'hash': json['hash'],
        'stateRootHash': json['state_root_hash'],
        'eventRootHash': json['event_root_hash'],
        'gasUsed': json['gas_used'],
        'success': json['success'],
        'vmStatus': json['vm_status'],
        'accumulatorRootHash': json['accumulator_root_hash'],
    };
}

export function OnChainTransactionInfoToJSON(value?: OnChainTransactionInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'hash': value.hash,
        'state_root_hash': value.stateRootHash,
        'event_root_hash': value.eventRootHash,
        'gas_used': value.gasUsed,
        'success': value.success,
        'vm_status': value.vmStatus,
        'accumulator_root_hash': value.accumulatorRootHash,
    };
}

