/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  BlockMetadataTransaction,
  BlockMetadataTransactionFromJSON,
  BlockMetadataTransactionFromJSONTyped,
  BlockMetadataTransactionToJSON,
} from "./BlockMetadataTransaction";
import {
  GenesisTransaction,
  GenesisTransactionFromJSON,
  GenesisTransactionFromJSONTyped,
  GenesisTransactionToJSON,
} from "./GenesisTransaction";
import {
  UserTransaction,
  UserTransactionFromJSON,
  UserTransactionFromJSONTyped,
  UserTransactionToJSON,
} from "./UserTransaction";

/**
 * @type OnChainTransaction
 *
 * @export
 */
export type OnChainTransaction =
  | BlockMetadataTransaction
  | GenesisTransaction
  | UserTransaction;

export function OnChainTransactionFromJSON(json: any): OnChainTransaction {
  return OnChainTransactionFromJSONTyped(json, false);
}

export function OnChainTransactionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OnChainTransaction {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...BlockMetadataTransactionFromJSONTyped(json, true),
    ...GenesisTransactionFromJSONTyped(json, true),
    ...UserTransactionFromJSONTyped(json, true),
  };
}

export function OnChainTransactionToJSON(
  value?: OnChainTransaction | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ...BlockMetadataTransactionToJSON(value),
    ...GenesisTransactionToJSON(value),
    ...UserTransactionToJSON(value),
  };
}
