/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from "../runtime";
import {
  MoveScript,
  MoveScriptFromJSON,
  MoveScriptFromJSONTyped,
  MoveScriptToJSON,
} from "./MoveScript";

/**
 *
 * @export
 * @interface Script
 */
export interface Script {
  /**
   *
   * @type {MoveScript}
   * @memberof Script
   */
  code: MoveScript;
  /**
   *
   * @type {Array<string>}
   * @memberof Script
   */
  typeArguments: Array<string>;
  /**
   *
   * @type {Array<any>}
   * @memberof Script
   */
  arguments: Array<any>;
}

export function ScriptFromJSON(json: any): Script {
  return ScriptFromJSONTyped(json, false);
}

export function ScriptFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Script {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    code: MoveScriptFromJSON(json["code"]),
    typeArguments: json["type_arguments"],
    arguments: json["arguments"],
  };
}

export function ScriptToJSON(value?: Script | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    code: MoveScriptToJSON(value.code),
    type_arguments: value.typeArguments,
    arguments: value.arguments,
  };
}
