/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Script,
    ScriptFromJSON,
    ScriptFromJSONTyped,
    ScriptToJSON,
} from './Script';

/**
 * 
 * @export
 * @interface ScriptWriteSet
 */
export interface ScriptWriteSet {
    /**
     * 
     * @type {string}
     * @memberof ScriptWriteSet
     */
    type: string;
    /**
     * Hex-encoded 16 bytes Diem account address.
     * 
     * Prefixed with `0x` and leading zeros are trimmed.
     * 
     * See [doc](https://diem.github.io/move/address.html) for more details.
     * @type {string}
     * @memberof ScriptWriteSet
     */
    executeAs: string;
    /**
     * 
     * @type {Script}
     * @memberof ScriptWriteSet
     */
    script: Script;
}

export function ScriptWriteSetFromJSON(json: any): ScriptWriteSet {
    return ScriptWriteSetFromJSONTyped(json, false);
}

export function ScriptWriteSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScriptWriteSet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'executeAs': json['execute_as'],
        'script': ScriptFromJSON(json['script']),
    };
}

export function ScriptWriteSetToJSON(value?: ScriptWriteSet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'execute_as': value.executeAs,
        'script': ScriptToJSON(value.script),
    };
}

