/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from "../runtime";
/**
 *
 * @export
 * @interface ScriptFunctionPayload
 */
export interface ScriptFunctionPayload {
  /**
   *
   * @type {string}
   * @memberof ScriptFunctionPayload
   */
  type: string;
  /**
   * Script function id is string representation of a script function defined on-chain.
   *
   * Format: `{address}::{module name}::{function name}`
   *
   * Both `module name` and `function name` are case sensitive.
   * @type {string}
   * @memberof ScriptFunctionPayload
   */
  _function: string;
  /**
   * Generic type arguments required by the script function.
   * @type {Array<string>}
   * @memberof ScriptFunctionPayload
   */
  typeArguments: Array<string>;
  /**
   * The script function arguments.
   * @type {Array<any>}
   * @memberof ScriptFunctionPayload
   */
  arguments: Array<any>;
}

export function ScriptFunctionPayloadFromJSON(
  json: any,
): ScriptFunctionPayload {
  return ScriptFunctionPayloadFromJSONTyped(json, false);
}

export function ScriptFunctionPayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ScriptFunctionPayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: json["type"],
    _function: json["function"],
    typeArguments: json["type_arguments"],
    arguments: json["arguments"],
  };
}

export function ScriptFunctionPayloadToJSON(
  value?: ScriptFunctionPayload | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: value.type,
    function: value._function,
    type_arguments: value.typeArguments,
    arguments: value.arguments,
  };
}
