/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Ed25519Signature,
    Ed25519SignatureFromJSON,
    Ed25519SignatureFromJSONTyped,
    Ed25519SignatureToJSON,
} from './Ed25519Signature';
import {
    MultiAgentSignature,
    MultiAgentSignatureFromJSON,
    MultiAgentSignatureFromJSONTyped,
    MultiAgentSignatureToJSON,
} from './MultiAgentSignature';
import {
    MultiEd25519Signature,
    MultiEd25519SignatureFromJSON,
    MultiEd25519SignatureFromJSONTyped,
    MultiEd25519SignatureToJSON,
} from './MultiEd25519Signature';

/**
 * @type TransactionSignature
 * 
 * @export
 */
export type TransactionSignature = Ed25519Signature | MultiAgentSignature | MultiEd25519Signature;

export function TransactionSignatureFromJSON(json: any): TransactionSignature {
    return TransactionSignatureFromJSONTyped(json, false);
}

export function TransactionSignatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionSignature {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...Ed25519SignatureFromJSONTyped(json, true), ...MultiAgentSignatureFromJSONTyped(json, true), ...MultiEd25519SignatureFromJSONTyped(json, true) };
}

export function TransactionSignatureToJSON(value?: TransactionSignature | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return { ...Ed25519SignatureToJSON(value), ...MultiAgentSignatureToJSON(value), ...MultiEd25519SignatureToJSON(value) };
}

