/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Event,
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
} from './Event';
import {
    OnChainTransactionInfo,
    OnChainTransactionInfoFromJSON,
    OnChainTransactionInfoFromJSONTyped,
    OnChainTransactionInfoToJSON,
} from './OnChainTransactionInfo';
import {
    TransactionPayload,
    TransactionPayloadFromJSON,
    TransactionPayloadFromJSONTyped,
    TransactionPayloadToJSON,
} from './TransactionPayload';
import {
    TransactionSignature,
    TransactionSignatureFromJSON,
    TransactionSignatureFromJSONTyped,
    TransactionSignatureToJSON,
} from './TransactionSignature';
import {
    UserTransactionAllOf,
    UserTransactionAllOfFromJSON,
    UserTransactionAllOfFromJSONTyped,
    UserTransactionAllOfToJSON,
} from './UserTransactionAllOf';
import {
    UserTransactionRequest,
    UserTransactionRequestFromJSON,
    UserTransactionRequestFromJSONTyped,
    UserTransactionRequestToJSON,
} from './UserTransactionRequest';
import {
    UserTransactionSignature,
    UserTransactionSignatureFromJSON,
    UserTransactionSignatureFromJSONTyped,
    UserTransactionSignatureToJSON,
} from './UserTransactionSignature';

/**
 * 
 * @export
 * @interface UserTransaction
 */
export interface UserTransaction {
    /**
     * 
     * @type {string}
     * @memberof UserTransaction
     */
    type: string;
    /**
     * 
     * @type {Array<Event>}
     * @memberof UserTransaction
     */
    events: Array<Event>;
    /**
     * Timestamp in microseconds, e.g. ledger / block creation timestamp.
     * @type {string}
     * @memberof UserTransaction
     */
    timestamp: string;
    /**
     * Hex-encoded 16 bytes Diem account address.
     * 
     * Prefixed with `0x` and leading zeros are trimmed.
     * 
     * See [doc](https://diem.github.io/move/address.html) for more details.
     * @type {string}
     * @memberof UserTransaction
     */
    sender: string;
    /**
     * Unsiged int64 type value
     * @type {string}
     * @memberof UserTransaction
     */
    sequenceNumber: string;
    /**
     * Unsiged int64 type value
     * @type {string}
     * @memberof UserTransaction
     */
    maxGasAmount: string;
    /**
     * Unsiged int64 type value
     * @type {string}
     * @memberof UserTransaction
     */
    gasUnitPrice: string;
    /**
     * 
     * @type {string}
     * @memberof UserTransaction
     */
    gasCurrencyCode: string;
    /**
     * Timestamp in seconds, e.g. transaction expiration timestamp.
     * @type {string}
     * @memberof UserTransaction
     */
    expirationTimestampSecs: string;
    /**
     * 
     * @type {TransactionPayload}
     * @memberof UserTransaction
     */
    payload: TransactionPayload;
    /**
     * 
     * @type {TransactionSignature}
     * @memberof UserTransaction
     */
    signature: TransactionSignature;
    /**
     * Unsiged int64 type value
     * @type {string}
     * @memberof UserTransaction
     */
    version: string;
    /**
     * All bytes data are represented as hex-encoded string prefixed with `0x` and fulfilled with
     * two hex digits per byte.
     * 
     * Different with `Address` type, hex-encoded bytes should not trim any zeros.
     * @type {string}
     * @memberof UserTransaction
     */
    hash: string;
    /**
     * All bytes data are represented as hex-encoded string prefixed with `0x` and fulfilled with
     * two hex digits per byte.
     * 
     * Different with `Address` type, hex-encoded bytes should not trim any zeros.
     * @type {string}
     * @memberof UserTransaction
     */
    stateRootHash: string;
    /**
     * All bytes data are represented as hex-encoded string prefixed with `0x` and fulfilled with
     * two hex digits per byte.
     * 
     * Different with `Address` type, hex-encoded bytes should not trim any zeros.
     * @type {string}
     * @memberof UserTransaction
     */
    eventRootHash: string;
    /**
     * Unsiged int64 type value
     * @type {string}
     * @memberof UserTransaction
     */
    gasUsed: string;
    /**
     * Transaction execution result (success: true, failure: false).
     * See `vm_status` for human readable error message from Diem VM.
     * @type {boolean}
     * @memberof UserTransaction
     */
    success: boolean;
    /**
     * Human readable transaction execution result message from Diem VM.
     * @type {string}
     * @memberof UserTransaction
     */
    vmStatus: string;
    /**
     * All bytes data are represented as hex-encoded string prefixed with `0x` and fulfilled with
     * two hex digits per byte.
     * 
     * Different with `Address` type, hex-encoded bytes should not trim any zeros.
     * @type {string}
     * @memberof UserTransaction
     */
    accumulatorRootHash: string;
}

export function UserTransactionFromJSON(json: any): UserTransaction {
    return UserTransactionFromJSONTyped(json, false);
}

export function UserTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserTransaction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'events': ((json['events'] as Array<any> || []).map(EventFromJSON)),
        'timestamp': json['timestamp'],
        'sender': json['sender'],
        'sequenceNumber': json['sequence_number'],
        'maxGasAmount': json['max_gas_amount'],
        'gasUnitPrice': json['gas_unit_price'],
        'gasCurrencyCode': json['gas_currency_code'],
        'expirationTimestampSecs': json['expiration_timestamp_secs'],
        'payload': TransactionPayloadFromJSON(json['payload']),
        'signature': TransactionSignatureFromJSON(json['signature']),
        'version': json['version'],
        'hash': json['hash'],
        'stateRootHash': json['state_root_hash'],
        'eventRootHash': json['event_root_hash'],
        'gasUsed': json['gas_used'],
        'success': json['success'],
        'vmStatus': json['vm_status'],
        'accumulatorRootHash': json['accumulator_root_hash'],
    };
}

export function UserTransactionToJSON(value?: UserTransaction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'events': ((value.events as Array<any> || []).map(EventToJSON)),
        'timestamp': value.timestamp,
        'sender': value.sender,
        'sequence_number': value.sequenceNumber,
        'max_gas_amount': value.maxGasAmount,
        'gas_unit_price': value.gasUnitPrice,
        'gas_currency_code': value.gasCurrencyCode,
        'expiration_timestamp_secs': value.expirationTimestampSecs,
        'payload': TransactionPayloadToJSON(value.payload),
        'signature': TransactionSignatureToJSON(value.signature),
        'version': value.version,
        'hash': value.hash,
        'state_root_hash': value.stateRootHash,
        'event_root_hash': value.eventRootHash,
        'gas_used': value.gasUsed,
        'success': value.success,
        'vm_status': value.vmStatus,
        'accumulator_root_hash': value.accumulatorRootHash,
    };
}

