/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from "../runtime";
import {
  TransactionSignature,
  TransactionSignatureFromJSON,
  TransactionSignatureFromJSONTyped,
  TransactionSignatureToJSON,
} from "./TransactionSignature";

/**
 * This schema is used for appending `signature` field to another schema.
 * @export
 * @interface UserTransactionSignature
 */
export interface UserTransactionSignature {
  /**
   *
   * @type {TransactionSignature}
   * @memberof UserTransactionSignature
   */
  signature: TransactionSignature;
}

export function UserTransactionSignatureFromJSON(
  json: any,
): UserTransactionSignature {
  return UserTransactionSignatureFromJSONTyped(json, false);
}

export function UserTransactionSignatureFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserTransactionSignature {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    signature: TransactionSignatureFromJSON(json["signature"]),
  };
}

export function UserTransactionSignatureToJSON(
  value?: UserTransactionSignature | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    signature: TransactionSignatureToJSON(value.signature),
  };
}
