/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Event,
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
} from './Event';

/**
 * 
 * @export
 * @interface UserTransactionAllOf
 */
export interface UserTransactionAllOf {
    /**
     * 
     * @type {string}
     * @memberof UserTransactionAllOf
     */
    type: string;
    /**
     * 
     * @type {Array<Event>}
     * @memberof UserTransactionAllOf
     */
    events: Array<Event>;
    /**
     * Timestamp in microseconds, e.g. ledger / block creation timestamp.
     * @type {string}
     * @memberof UserTransactionAllOf
     */
    timestamp: string;
}

export function UserTransactionAllOfFromJSON(json: any): UserTransactionAllOf {
    return UserTransactionAllOfFromJSONTyped(json, false);
}

export function UserTransactionAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserTransactionAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'events': ((json['events'] as Array<any> || []).map(EventFromJSON)),
        'timestamp': json['timestamp'],
    };
}

export function UserTransactionAllOfToJSON(value?: UserTransactionAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'events': ((value.events as Array<any> || []).map(EventToJSON)),
        'timestamp': value.timestamp,
    };
}

