/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    DirectWriteSet,
    DirectWriteSetFromJSON,
    DirectWriteSetFromJSONTyped,
    DirectWriteSetToJSON,
} from './DirectWriteSet';
import {
    ScriptWriteSet,
    ScriptWriteSetFromJSON,
    ScriptWriteSetFromJSONTyped,
    ScriptWriteSetToJSON,
} from './ScriptWriteSet';

/**
 * @type WriteSet
 * 
 * @export
 */
export type WriteSet = DirectWriteSet | ScriptWriteSet;

export function WriteSetFromJSON(json: any): WriteSet {
    return WriteSetFromJSONTyped(json, false);
}

export function WriteSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriteSet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...DirectWriteSetFromJSONTyped(json, true), ...ScriptWriteSetFromJSONTyped(json, true) };
}

export function WriteSetToJSON(value?: WriteSet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return { ...DirectWriteSetToJSON(value), ...ScriptWriteSetToJSON(value) };
}

