/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  DeleteModule,
  DeleteModuleFromJSON,
  DeleteModuleFromJSONTyped,
  DeleteModuleToJSON,
} from "./DeleteModule";
import {
  DeleteResource,
  DeleteResourceFromJSON,
  DeleteResourceFromJSONTyped,
  DeleteResourceToJSON,
} from "./DeleteResource";
import {
  WriteModule,
  WriteModuleFromJSON,
  WriteModuleFromJSONTyped,
  WriteModuleToJSON,
} from "./WriteModule";
import {
  WriteResource,
  WriteResourceFromJSON,
  WriteResourceFromJSONTyped,
  WriteResourceToJSON,
} from "./WriteResource";

/**
 * @type WriteSetChange
 *
 * @export
 */
export type WriteSetChange =
  | DeleteModule
  | DeleteResource
  | WriteModule
  | WriteResource;

export function WriteSetChangeFromJSON(json: any): WriteSetChange {
  return WriteSetChangeFromJSONTyped(json, false);
}

export function WriteSetChangeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WriteSetChange {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...DeleteModuleFromJSONTyped(json, true),
    ...DeleteResourceFromJSONTyped(json, true),
    ...WriteModuleFromJSONTyped(json, true),
    ...WriteResourceFromJSONTyped(json, true),
  };
}

export function WriteSetChangeToJSON(value?: WriteSetChange | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ...DeleteModuleToJSON(value),
    ...DeleteResourceToJSON(value),
    ...WriteModuleToJSON(value),
    ...WriteResourceToJSON(value),
  };
}
