/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Diem Dev API Specification
 * Diem Dev API is REST API for client applications to interact the Diem blockchain. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccountResource,
    AccountResourceFromJSON,
    AccountResourceFromJSONTyped,
    AccountResourceToJSON,
} from './AccountResource';

/**
 * Write account resource
 * @export
 * @interface WriteResource
 */
export interface WriteResource {
    /**
     * 
     * @type {string}
     * @memberof WriteResource
     */
    type: string;
    /**
     * Hex-encoded 16 bytes Diem account address.
     * 
     * Prefixed with `0x` and leading zeros are trimmed.
     * 
     * See [doc](https://diem.github.io/move/address.html) for more details.
     * @type {string}
     * @memberof WriteResource
     */
    address: string;
    /**
     * 
     * @type {AccountResource}
     * @memberof WriteResource
     */
    data: AccountResource;
}

export function WriteResourceFromJSON(json: any): WriteResource {
    return WriteResourceFromJSONTyped(json, false);
}

export function WriteResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriteResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'address': json['address'],
        'data': AccountResourceFromJSON(json['data']),
    };
}

export function WriteResourceToJSON(value?: WriteResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'address': value.address,
        'data': AccountResourceToJSON(value.data),
    };
}

